FROM mpsamurai/neochi-dev-base:20190424-arm32v6

COPY ./requirements.txt /tmp
RUN pip --no-cache-dir install -r /tmp/requirements.txt && rm /tmp/requirements.txt

WORKDIR /code
COPY ./src /code

CMD ["python", "main.py"]
