version: "3"

services:
  redis:
    image: arm32v6/redis:5-alpine
    ports:
      - 6379:6379
  ir-receiver:
    build:
      context: .
      dockerfile: Dockerfile-raspbian
    volumes:
      - ./src:/code
      - ../neochi-core/src/neochi:/code/neochi
      - ./data:/data
    network_mode: "host"
    depends_on:
      - redis
