FROM mpsamurai/neochi-dev-base:20190424-x64

COPY ./requirements.txt /tmp
RUN pip --no-cache-dir install pigpio nose coverage

WORKDIR /code

CMD ["nosetests", "--with-coverage", "--cover-html", "--cover-package", "test/test_main.py"]